// Single source of truth for every partner merchant. The home carousel, the
// "Top Wisata Batam" grid, and the /merchants directory all read from here.
export type Merchant = {
  id: number;
  name: string;
  category: string;
  rating: number;
  reviews: number;
  originalPrice: string;
  salePrice: string;
  tag: string;
  location: string;
  lat: number;
  lng: number;
  desc: string;
  photo: string;
};

export const merchants: Merchant[] = [
  {
    id: 1,
    name: "Golden Prawn Seafood",
    category: "Seafood",
    rating: 4.9,
    reviews: 1240,
    originalPrice: "Rp 200.000",
    salePrice: "S$ 14",
    tag: "Best Seller",
    location: "Harbour Bay, Batam",
    lat: 1.1476, lng: 104.0165,
    desc: "Fresh tiger prawns, chili crab & more — cooked live at the harbour.",
    photo: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 2,
    name: "Nagoya Wellness Spa",
    category: "Spa",
    rating: 4.8,
    reviews: 890,
    originalPrice: "Rp 350.000",
    salePrice: "S$ 24",
    tag: "Top Rated",
    location: "Nagoya Hill, Batam",
    lat: 1.1345, lng: 104.0208,
    desc: "Full-body aromatherapy massage and scrub in a luxury setting.",
    photo: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 3,
    name: "Harbour Bay Mall",
    category: "Shopping",
    rating: 4.7,
    reviews: 2100,
    originalPrice: "Rp 150.000",
    salePrice: "S$ 10",
    tag: "Popular",
    location: "Harbour Bay, Batam",
    lat: 1.1466, lng: 104.0150,
    desc: "Branded goods, electronics & local fashion at duty-free prices.",
    photo: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 4,
    name: "Batam Night Market",
    category: "Street Food",
    rating: 4.8,
    reviews: 650,
    originalPrice: "Rp 120.000",
    salePrice: "S$ 8",
    tag: "Must Try",
    location: "Nagoya, Batam",
    lat: 1.1300, lng: 104.0180,
    desc: "Satay, nasi goreng, es teler — the authentic Batam street experience.",
    photo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 5,
    name: "Avani Spa Resort",
    category: "Spa",
    rating: 4.9,
    reviews: 320,
    originalPrice: "Rp 500.000",
    salePrice: "S$ 34",
    tag: "Premium",
    location: "Nongsa, Batam",
    lat: 1.1900, lng: 104.1000,
    desc: "Resort-grade spa ritual with sea view. Pure indulgence.",
    photo: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 6,
    name: "Batam Fresh Crab House",
    category: "Seafood",
    rating: 4.7,
    reviews: 780,
    originalPrice: "Rp 280.000",
    salePrice: "S$ 19",
    tag: "New",
    location: "Sekupang, Batam",
    lat: 1.1230, lng: 103.9270,
    desc: "Butter crab and salted egg crab straight from the sea — daily catch.",
    photo: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 7,
    name: "Harris Resort Waterfront",
    category: "Hotel",
    rating: 4.7,
    reviews: 1560,
    originalPrice: "Rp 1.400.000",
    salePrice: "S$ 96",
    tag: "Stay & Play",
    location: "Batam Centre, Batam",
    lat: 1.1190, lng: 104.0430,
    desc: "Waterfront resort with pool, breakfast and ferry-terminal pickup.",
    photo: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 8,
    name: "Nagoya Hill Boutique Stay",
    category: "Hotel",
    rating: 4.6,
    reviews: 940,
    originalPrice: "Rp 700.000",
    salePrice: "S$ 48",
    tag: "Budget Stay",
    location: "Nagoya, Batam",
    lat: 1.1360, lng: 104.0175,
    desc: "Walk to Nagoya Hill Mall. Clean rooms, early check-in on request.",
    photo: "https://images.unsplash.com/photo-1560200353-ce0a76b1d438?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 9,
    name: "Barelang Bridge Viewpoint",
    category: "Attraction",
    rating: 4.8,
    reviews: 1780,
    originalPrice: "Rp 100.000",
    salePrice: "S$ 6",
    tag: "Photo Spot",
    location: "Barelang, Batam",
    lat: 1.0040, lng: 104.0500,
    desc: "Sunset over the iconic Barelang bridge — the shot everyone wants.",
    photo: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 10,
    name: "Batam Miniature Park",
    category: "Attraction",
    rating: 4.5,
    reviews: 1120,
    originalPrice: "Rp 80.000",
    salePrice: "S$ 5",
    tag: "Family Fun",
    location: "Sungai Panas, Batam",
    lat: 1.1290, lng: 104.0480,
    desc: "Cultural houses, cable car and a lake — easy half-day with kids.",
    photo: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 11,
    name: "Nongsa Beach Escape",
    category: "Attraction",
    rating: 4.7,
    reviews: 860,
    originalPrice: "Rp 180.000",
    salePrice: "S$ 11",
    tag: "Weekend",
    location: "Nongsa, Batam",
    lat: 1.1980, lng: 104.1050,
    desc: "Quiet northeast shore, watersports and seafood shacks on the sand.",
    photo: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 12,
    name: "Kelong Seafood Village",
    category: "Seafood",
    rating: 4.6,
    reviews: 1340,
    originalPrice: "Rp 250.000",
    salePrice: "S$ 17",
    tag: "Best Seller",
    location: "Tanjung Piayu, Batam",
    lat: 1.1050, lng: 104.0850,
    desc: "Dine over the water on a traditional kelong. Book sunset seating.",
    photo: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=700&q=80&auto=format&fit=crop",
  },
  {
    id: 13,
    name: "Otak-Otak Street Corner",
    category: "Street Food",
    rating: 4.5,
    reviews: 420,
    originalPrice: "Rp 60.000",
    salePrice: "S$ 4",
    tag: "Local Favourite",
    location: "Nagoya, Batam",
    lat: 1.1320, lng: 104.0210,
    desc: "Grilled otak-otak and goreng pisang — the classic Batam snack stop.",
    photo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=700&q=80&auto=format&fit=crop",
  },
];

export const merchantDetails: Record<number, {
  hours: string;
  highlights: string[];
  includes: string[];
  promo?: string;
}> = {
  1: {
    hours: "11:00 – 22:00 WIB",
    highlights: ["Live seafood selection", "Harbourfront dining", "Halal-friendly menu"],
    includes: ["S$ 14 dining credit", "Freshly prepared seafood", "Air-conditioned seating"],
    promo: "Weekday diners receive a complimentary iced tea.",
  },
  2: {
    hours: "10:00 – 22:00 WIB",
    highlights: ["60-minute aromatherapy", "Private treatment room", "Certified therapists"],
    includes: ["Aromatherapy massage", "Warm towel welcome", "Herbal tea after treatment"],
    promo: "Add a body scrub at 20% off before 15:00.",
  },
  3: {
    hours: "10:00 – 22:00 WIB",
    highlights: ["Duty-free shopping", "Local fashion finds", "Near ferry terminal"],
    includes: ["S$ 10 shopping credit", "Mall directory", "Wi-Fi access"],
  },
  4: {
    hours: "17:00 – 23:00 WIB",
    highlights: ["Local street food", "Evening atmosphere", "Easy Nagoya access"],
    includes: ["S$ 8 food credit", "Vendor recommendations", "Flexible redemption"],
    promo: "Redeem Sunday–Thursday for a bonus dessert.",
  },
  5: {
    hours: "09:00 – 21:00 WIB",
    highlights: ["Sea-view treatment", "Resort ambience", "Premium essential oils"],
    includes: ["75-minute spa ritual", "Steam-room access", "Post-treatment refreshment"],
  },
  6: {
    hours: "11:00 – 22:00 WIB",
    highlights: ["Daily local catch", "Signature salted egg crab", "Family-friendly tables"],
    includes: ["S$ 19 dining credit", "Fresh crab selection", "Table reservation"],
  },
  7: {
    hours: "24-hour front desk",
    highlights: ["Waterfront pool", "Breakfast included", "Ferry-terminal pickup"],
    includes: ["1-night stay voucher", "Breakfast for two", "Late checkout to 14:00"],
    promo: "Free upgrade to sea-view room on weekday check-ins.",
  },
  8: {
    hours: "24-hour front desk",
    highlights: ["Walk to Nagoya Hill Mall", "Early check-in", "Airport transfer desk"],
    includes: ["1-night stay voucher", "Welcome drink", "Wi-Fi access"],
  },
  9: {
    hours: "Open 24 hours",
    highlights: ["Iconic bridge panorama", "Best at sunset", "Free parking nearby"],
    includes: ["S$ 6 photo-credit", "Viewpoint access", "Local guide tips"],
    promo: "Golden-hour slot before 18:30 gets a free iced coconut.",
  },
  10: {
    hours: "09:00 – 18:00 WIB",
    highlights: ["Cultural houses", "Cable car ride", "Lakeside walk"],
    includes: ["S$ 5 park entry", "Cable car one-way", "Site map"],
  },
  11: {
    hours: "07:00 – 19:00 WIB",
    highlights: ["Quiet northeast shore", "Watersports on site", "Beachfront seafood shacks"],
    includes: ["S$ 11 beach credit", "Sun lounger", "Shower & changing room"],
    promo: "Kayak rental half price after 15:00.",
  },
  12: {
    hours: "11:00 – 22:00 WIB",
    highlights: ["Dine over the water", "Sunset seating", "Live seafood tanks"],
    includes: ["S$ 17 dining credit", "Kelong table booking", "Fresh catch selection"],
  },
  13: {
    hours: "14:00 – 22:00 WIB",
    highlights: ["Grilled otak-otak", "Goreng pisang", "Street-side snack stop"],
    includes: ["S$ 4 food credit", "Snack of choice", "Takeaway box"],
  },
};

export const tagColors: Record<string, string> = {
  "Best Seller":     "bg-orange-500",
  "Top Rated":       "bg-purple-500",
  Popular:           "bg-emerald-600",
  "Must Try":        "bg-amber-500",
  Premium:           "bg-pink-600",
  New:               "bg-blue-500",
  "Stay & Play":     "bg-indigo-600",
  "Budget Stay":     "bg-teal-600",
  "Photo Spot":      "bg-fuchsia-600",
  "Family Fun":      "bg-cyan-600",
  Weekend:           "bg-lime-600",
  "Local Favourite": "bg-rose-500",
};